config_form.admin:
  title: 'Config Form menu title'
  description: 'Administration tools.'
  route_name: config_form.admin
  parent: system.admin_config
config_form.settings:
  title:  'Config form'
  description: 'Example config form'
  route_name: config_form.settings
  parent: config_form.admin
